# Generated by Django 5.2 on 2025-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disciplinar',
            new_name='Disciplina',
        ),
        migrations.AlterField(
            model_name='professor',
            name='ni',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
