# Generated by Django 5.2 on 2025-05-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_disciplinar_disciplina_alter_professor_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
