# Generated by Django 5.2 on 2025-05-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_professor_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='ni',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
