# Generated by Django 5.2 on 2025-05-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_professor_data_contratacao_alter_professor_ni_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this user belongs to.', related_name='professor_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='ni',
            field=models.PositiveIntegerField(default=99999, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reservadeambiente',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='reservadeambiente',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
    ]
