# Generated by Django 5.2 on 2025-05-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_disciplina_carga_horaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='nome',
            new_name='name',
        ),
    ]
