# Generated by Django 5.1.6 on 2025-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appitens', '0002_item_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(),
        ),
    ]
